### PR TITLE
Provide generic signed /unsigned type conversion

### LINKED ISSUE #735: Compile error with xsimd on on ARM64/Apple Silicon
Here is the traceback, unfortunately I cannot share a bigger reproducible due to proprietary code, but feel free to ask for more information.

The xtensor-dependent program compiles fine with xsimd off.

```
error: no viable conversion from returned value of type 'xsimd::batch_bool<float, xsimd::neon64>' to function return type 'simd_return_type<float>' (aka 'xsimd::batch<float>')
```

### PR DESCRIPTION
**Pull request by serge-sans-paille**
A reinterpret_cast is usually the way to go. For the range of value when it's valid in C, we achieve the same behavior for batches.

Fix #735

### CODE REVIEW

File: include/xsimd/arch/generic/xsimd_generic_details.hpp [hunk 1]
```diff
@@ -135,6 +135,51 @@ namespace xsimd
...
+            {
+                return bitwise_cast<uint16_t>(self);
+            }
+            template <class A>
+            inline batch<uint32_t, A> fast_cast(batch<int32_t, A> const& self, batch<uint32_t, A> const&, requires_arch<generic>) noexcept
+            {
+                return bitwise_cast<uint32_t>(self);
+            }
+            template <class A>
+            inline batch<uint64_t, A> fast_cast(batch<uint64_t, A> const& self, batch<int64_t, A> const&, requires_arch<generic>) noexcept
```
Comment (JohanMabille) [inline include/xsimd/arch/generic/xsimd_generic_details.hpp:157]: Looks like you inverted the arguments here.

File: include/xsimd/arch/generic/xsimd_generic_details.hpp [hunk 2]
```diff
@@ -135,6 +135,51 @@ namespace xsimd
...
+            {
+                return bitwise_cast<int64_t>(self);
```
Comment (JohanMabille) [inline include/xsimd/arch/generic/xsimd_generic_details.hpp:159]: This should bitwise cast to `uint64_t`

**Review by JohanMabille — CHANGES_REQUESTED** [review]

File: include/xsimd/arch/generic/xsimd_generic_details.hpp (hunk 1 above)
Comment (JohanMabille) [reply include/xsimd/arch/generic/xsimd_generic_details.hpp:157]: (But then I wonder why the tests are passing in the build where we force not instruction set)

Comment (JohanMabille) [reply include/xsimd/arch/generic/xsimd_generic_details.hpp:157]: This one is not fixed in your latest commit

**Comment by serge-sans-paille** [comment]
It now is ;-)

**Review by JohanMabille — APPROVED** [review]

**Comment by JohanMabille** [comment]
The fialure is unrelated to the changes.
