### PR TITLE
Fix integer sign during shift

### LINKED ISSUE #717: signed shift result (0x80000000) sets the sign bit of the shift expression's type ('int') and becomes negative
```
xsimd/include/xsimd/arch/xsimd_sse2.hpp:545:38: error: signed shift result (0x80000000) sets the sign bit of the shift expression's type ('int') and becomes negative [-Werror,-Wshift-sign-overflow]
                    _mm_set1_epi32(1 << 31)));
                                   ~ ^  ~~
```

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Fix #717

### CODE REVIEW

File: include/xsimd/arch/xsimd_avx512f.hpp [hunk 1]
```diff
@@ -1317,7 +1317,7 @@ namespace xsimd
                 alignas(avx2::alignment()) uint8_t buffer[64];
                 // FIXME: ultra inefficient
                 for (int i = 0; i < 64; ++i)
-                    buffer[i] = cond.data & ((uint64_t)1 << i) ? 0xFF : 0;
```
Comment (Yuhta) [inline include/xsimd/arch/xsimd_avx512f.hpp:1320]: This was fine

**Review by Yuhta — APPROVED** [review]

File: include/xsimd/arch/xsimd_avx512f.hpp (hunk 1 above)
Comment (serge-sans-paille) [reply include/xsimd/arch/xsimd_avx512f.hpp:1320]: Yeah, that was just for consistency with the remaining part of the code.
